export const mockFaqData = [
  {
    question_id: "FAQ-ROOT-ORDER",
    question_text: "I have an issue with my order",
    issue_type: "order",
    type: "root",
    next_questions: ["FAQ-ORDER-STATUS", "FAQ-ORDER-DELAY", "FAQ-ORDER-CANCEL"],
    priority: 1,
    created_by: "system",
  },
  {
    question_id: "FAQ-ROOT-PAYMENT",
    question_text: "I have a payment related issue",
    issue_type: "payment",
    type: "root",
    next_questions: ["FAQ-PAYMENT-FAILED", "FAQ-PAYMENT-DEDUCTED", "FAQ-PAYMENT-REFUND"],
    priority: 2,
    created_by: "system",
  },
  {
    question_id: "FAQ-ROOT-RETURNS",
    question_text: "I want to return or replace a product",
    issue_type: "returns",
    type: "root",
    next_questions: ["FAQ-RETURN-POLICY", "FAQ-RETURN-PROCESS", "FAQ-REPLACEMENT-PROCESS"],
    priority: 3,
    created_by: "system",
  },
  {
    question_id: "FAQ-ROOT-ACCOUNT",
    question_text: "I need help with my account",
    issue_type: "account",
    type: "root",
    next_questions: ["FAQ-ACCOUNT-LOGIN", "FAQ-ACCOUNT-ADDRESS", "FAQ-ACCOUNT-ORDERS"],
    priority: 4,
    created_by: "system",
  },

  {
    question_id: "FAQ-ORDER-STATUS",
    question_text: "Where is my order?",
    answer_text: "You can check your order status from the 'My Orders' section in your account.",
    issue_type: "order",
    type: "leaf",
    parent_question_id: "FAQ-ROOT-ORDER",
    escalation_allowed: true,
    keywords: ["order status", "track order"],
  },
  {
    question_id: "FAQ-ORDER-DELAY",
    question_text: "My order is delayed",
    answer_text:
      "Orders are delivered within the estimated delivery date. Delays may occur due to unforeseen logistics issues.",
    issue_type: "order",
    type: "leaf",
    parent_question_id: "FAQ-ROOT-ORDER",
    escalation_allowed: true,
    keywords: ["order delayed", "late delivery"],
  },
  {
    question_id: "FAQ-ORDER-CANCEL",
    question_text: "Can I cancel my order?",
    answer_text: "Orders can be cancelled before they are shipped. Once shipped, cancellation is not possible.",
    issue_type: "order",
    type: "leaf",
    parent_question_id: "FAQ-ROOT-ORDER",
    escalation_allowed: true,
    keywords: ["cancel order"],
  },

  {
    question_id: "FAQ-PAYMENT-FAILED",
    question_text: "My payment failed",
    answer_text: "If a payment fails, please retry using another payment method.",
    issue_type: "payment",
    type: "leaf",
    parent_question_id: "FAQ-ROOT-PAYMENT",
    escalation_allowed: true,
    keywords: ["payment failed"],
  },
  {
    question_id: "FAQ-PAYMENT-DEDUCTED",
    question_text: "Payment deducted but order not placed",
    answer_text: "If the amount was deducted, it will be automatically refunded within 5–7 business days.",
    issue_type: "payment",
    type: "leaf",
    parent_question_id: "FAQ-ROOT-PAYMENT",
    escalation_allowed: true,
    keywords: ["payment deducted", "refund"],
  },
  {
    question_id: "FAQ-PAYMENT-REFUND",
    question_text: "When will I get my refund?",
    answer_text: "Refunds are processed within 5–7 business days after approval.",
    issue_type: "payment",
    type: "leaf",
    parent_question_id: "FAQ-ROOT-PAYMENT",
    escalation_allowed: true,
    keywords: ["refund status"],
  },

  {
    question_id: "FAQ-RETURN-POLICY",
    question_text: "What is your return policy?",
    answer_text: "Products can be returned within 7 days of delivery if unused and in original packaging.",
    issue_type: "returns",
    type: "leaf",
    parent_question_id: "FAQ-ROOT-RETURNS",
    escalation_allowed: true,
    keywords: ["return policy"],
  },
  {
    question_id: "FAQ-RETURN-PROCESS",
    question_text: "How do I return a product?",
    answer_text: "Go to 'My Orders', select the product and choose the return option.",
    issue_type: "returns",
    type: "leaf",
    parent_question_id: "FAQ-ROOT-RETURNS",
    escalation_allowed: true,
    keywords: ["return process"],
  },
  {
    question_id: "FAQ-REPLACEMENT-PROCESS",
    question_text: "How do I replace a product?",
    answer_text: "Replacement can be requested from the 'My Orders' section within 7 days of delivery.",
    issue_type: "returns",
    type: "leaf",
    parent_question_id: "FAQ-ROOT-RETURNS",
    escalation_allowed: true,
    keywords: ["replacement"],
  },

  {
    question_id: "FAQ-ACCOUNT-LOGIN",
    question_text: "I am unable to login",
    answer_text: "Please use the 'Forgot Password' option to reset your password.",
    issue_type: "account",
    type: "leaf",
    parent_question_id: "FAQ-ROOT-ACCOUNT",
    escalation_allowed: true,
    keywords: ["login issue"],
  },
  {
    question_id: "FAQ-ACCOUNT-ADDRESS",
    question_text: "How do I change my delivery address?",
    answer_text: "You can update your address from the 'My Account' section before placing an order.",
    issue_type: "account",
    type: "leaf",
    parent_question_id: "FAQ-ROOT-ACCOUNT",
    escalation_allowed: true,
    keywords: ["change address"],
  },
  {
    question_id: "FAQ-ACCOUNT-ORDERS",
    question_text: "Where can I see my previous orders?",
    answer_text: "All your previous orders are available under the 'My Orders' section.",
    issue_type: "account",
    type: "leaf",
    parent_question_id: "FAQ-ROOT-ACCOUNT",
    escalation_allowed: true,
    keywords: ["order history"],
  },
];
