import fs from "fs";
import path from "path";
import {
  createProductService,
  deleteProductService,
  downloadExcelTemplateService,
  getAllProductsService,
  getProductByUniqueIdService,
  updateProductService,
} from "./productServices.js";

export const createProductController = async (req, res) => {
  try {
    const tenantID = req.headers["x-tenant-id"];

    const data = req.body;

    let product_image;
    let product_images = [];

    if (req.files?.product_image && req.files.product_image.length > 0) {
      product_image = `/uploads/productsImages/${req.files.product_image[0].filename}`;
    }

    if (req.files?.product_images && req.files.product_images.length > 0) {
      product_images = req.files.product_images?.map((file) => `/uploads/productsImages/${file.filename}`);
    }

    console.log(product_image, "product_image");
    console.log(product_images, "product_images");

    const inputData = {
      ...data,
      product_image,
      product_images,
    };

    const createdProduct = await createProductService(tenantID, inputData);

    res.status(201).json({
      status: "Success",
      message: "Product created successfully",
      data: createdProduct,
    });
  } catch (error) {
    console.error("Product creation failed in controller ===>", error.message);
    res.status(500).json({
      status: "Failed",
      message: error.message,
      // error: error.message,
    });
  }
};

export const getAllProductsController = async (req, res) => {
  try {
    const filters = req.query;
    const tenantID = req.headers["x-tenant-id"];
    const { data, totalCount } = await getAllProductsService(tenantID, filters);

    res.status(200).json({
      status: "Success",
      message: "Products fetched successfully by search filters",
      totalCount,
      data,
    });
  } catch (error) {
    console.error("Product Search Controller Error ===>", error.message);
    res.status(500).json({
      status: "Failed",
      message: "Error fetching products",
      error: error.message,
    });
  }
};

// Product Id generated by admin
export const getProductByIdController = async (req, res) => {
  try {
    const { id } = req.params; // This is products_unique_ID
    const tenantID = req.headers["x-tenant-id"];

    if (!id) {
      return res.status(400).json({
        status: "Failed",
        message: "products_unique_ID is required in URL",
      });
    }

    const response = await getProductByUniqueIdService(tenantID, id);

    res.status(200).json({
      status: "Success",
      message: "Product fetched successfully",
      data: response,
    });
  } catch (error) {
    console.error("Error in getByIdProductsController ===>", error.message);
    res.status(500).json({
      status: "Failed",
      message: "Failed to fetch product",
      error: error.message,
    });
  }
};

export const updateProductController = async (req, res) => {
  try {
    const { id } = req.params;
    const productData = req.body;
    const tenantID = req.headers["x-tenant-id"];
    if (!id) {
      return res.status(400).json({
        status: "Failed",
        message: "products_unique_ID is required in URL",
      });
    }

    if (req.files) {
      if (req.files.product_image && req.files.product_image.length > 0) {
        productData.product_image = req.files.product_image[0].path;
      }

      if (req.files.product_images && req.files.product_images.length > 0) {
        productData.product_images = req.files.product_images.map((file) => file.path);
      }
    }

    const response = await updateProductService(tenantID, id, productData);

    res.status(200).json({
      status: "Success",
      message: "Product updated successfully",
      data: response,
    });
  } catch (error) {
    console.error("Product update failed in controller:", error);
    res.status(500).json({
      status: "Failed",
      message: "Product update failed",
      error: error.message,
    });
  }
};

export const deleteProductController = async (req, res) => {
  try {
    const { id } = req.params; // products_unique_ID
    const tenantID = req.headers["x-tenant-id"];

    if (!id) {
      return res.status(400).json({
        status: "Failed",
        message: "Product unique ID is required in URL",
      });
    }

    const existingProduct = await deleteProductService(tenantID, id);

    const deleteFileIfExists = (filePath) => {
      if (!filePath) return;

      let cleanedPath = filePath
        .replace(/\\/g, "/")
        .replace("/uploads/productsImages/", "/uploads/productImages/")
        .replace(/^\/+/, "");

      const fullPath = path.resolve(process.cwd(), cleanedPath);

      try {
        if (fs.existsSync(fullPath)) {
          fs.unlinkSync(fullPath);
          console.log("Deleted:", fullPath);
        } else {
          console.warn("File not found:", fullPath);
        }
      } catch (err) {
        console.warn("Failed to delete:", fullPath, err.message);
      }
    };

    // Delete main and multiple product images
    if (existingProduct.product_image) {
      deleteFileIfExists(existingProduct.product_image);
    }

    if (Array.isArray(existingProduct.product_images)) {
      existingProduct.product_images.forEach(deleteFileIfExists);
    }

    res.status(200).json({
      status: "Success",
      message: "Product deleted successfully",
      data: existingProduct,
    });
  } catch (error) {
    console.error("Delete Product Controller Error ===>", error.message);
    res.status(500).json({
      status: "Failed",
      message: "Error deleting product",
      error: error.message,
    });
  }
};

export const downloadExcelTemplateController = async (req, res) => {
  try {
    const tenantID = req.headers["x-tenant-id"];
    const { id: category_unique_ID } = req.params; // category_unique_ID

    const workbook = await downloadExcelTemplateService(tenantID, category_unique_ID);

    res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    res.setHeader("Content-Disposition", "attachment; filename=product_template.xlsx");

    await workbook.xlsx.write(res);
    res.end();
  } catch (error) {
    console.error("Error in downloadExcelTemplateController ===>", error.message);
    res.status(500).json({
      status: "Failed",
      message: "Error downloading Excel template",
      error: error.message,
    });
  }
};

// MongoDb id generated by db
// export const getProductByIdController = async (req, res) => {
//   try {
//     const { id } = req.params; // This is product id
//     const tenantID = req.headers["x-tenant-id"];

//     if (!id) {
//       return res.status(400).json({
//         status: "Failed",
//         message: "products_unique_ID is required in URL",
//       });
//     }

//     const response = await getProductByIdServices(tenantID, id);

//     res.status(200).json({
//       status: "Success",
//       message: "Product fetched successfully",
//       data: response,
//     });
//   } catch (error) {
//     console.error("Error in getProductByIdController ===>", error.message);
//     res.status(500).json({
//       status: "Failed",
//       message: "Failed to fetch product",
//       error: error.message,
//     });
//   }
// }

// export const getProductsBysubUniqeIDController = async (req, res) => {
//   try {
//     const { id } = req.params; // This ID is  Category unique ID
//     const tenantID = req.headers["x-tenant-id"];
//     if (!id) {
//       return res.status(400).json({
//         status: "Failed",
//         message: "subCategory_unique_ID is required in URL",
//       });
//     }

//     const response = await getProductsBySubUniqueIDServices(tenantID, id);

//     if (!response || response.length === 0) {
//       return res.status(404).json({
//         status: "Failed",
//         message: "No products found for this subCategory_unique_ID",
//       });
//     }

//     res.status(200).json({
//       status: "Success",
//       message: "Products fetched successfully by subCategory_unique_ID",
//       data: response,
//     });
//   } catch (error) {
//     console.error(
//       "Error in getProductsBysubUniqeIDController ===>",
//       error.message
//     );
//     res.status(500).json({
//       status: "Failed",
//       message: "Failed to fetch products",
//       error: error.message,
//     });
//   }
// };
